/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const UPGRADES = [
  {
    id: 'bear',
    name: 'Friendly Bear',
    description: 'A local bear helps you swipe salmon from the stream.',
    baseCost: 15,
    baseSps: 1,
    icon: '🐻',
  },
  {
    id: 'rod',
    name: 'Auto-Rod',
    description: 'A high-tech fishing rod that catches itself.',
    baseCost: 100,
    baseSps: 5,
    icon: '🎣',
  },
  {
    id: 'net',
    name: 'Drift Net',
    description: 'A large net that catches hundreds of passing salmon.',
    baseCost: 1100,
    baseSps: 18,
    icon: '🕸️',
  },
  {
    id: 'ladder',
    name: 'Salmon Ladder',
    description: 'Optimizes the migration path for maximum efficiency.',
    baseCost: 12000,
    baseSps: 65,
    icon: '🪜',
  },
  {
    id: 'hatchery',
    name: 'Industrial Hatchery',
    description: 'Brings salmon production into the 21st century.',
    baseCost: 130000,
    baseSps: 320,
    icon: '🏭',
  },
  {
    id: 'trawler',
    name: 'Ocean Trawler',
    description: 'A massive vessel harvesting the deep currents.',
    baseCost: 1450000,
    baseSps: 1500,
    icon: '🚢',
  },
  {
    id: 'portal',
    name: 'River Portal',
    description: 'Summons salmon from parallel river dimensions.',
    baseCost: 15500000,
    baseSps: 6500,
    icon: '🌀',
  },
  {
    id: 'moon',
    name: 'Lunar Tide Control',
    description: 'Control the tides to bring all salmon to your door.',
    baseCost: 180000000,
    baseSps: 25000,
    icon: '🌙',
  },
  {
    id: 'dna',
    name: 'DNA Sculptor',
    description: 'Rewrite the code of life for maximum salmon density.',
    baseCost: 2000000000,
    baseSps: 120000,
    icon: '🧬',
  },
  {
    id: 'galaxy',
    name: 'Galactic Stream',
    description: 'The entire Milky Way is now a salmon habitat.',
    baseCost: 25000000000,
    baseSps: 800000,
    icon: '🌌',
  },
  {
    id: 'quantum',
    name: 'Quantum Spawner',
    description: 'Salmon exists in every possible location simultaneously.',
    baseCost: 350000000000,
    baseSps: 5000000,
    icon: '⚛️',
  },
  {
    id: 'infinite',
    name: 'Infinite River Loop',
    description: 'A Mobius-strip river that flows back into itself forever.',
    baseCost: 5000000000000,
    baseSps: 35000000,
    icon: '♾️',
  },
  {
    id: 'ascended',
    name: 'Salmon Singularity',
    description: 'The moment where salmon and the universe become one.',
    baseCost: 75000000000000,
    baseSps: 250000000,
    icon: '👁️',
  },
];

export const NEWS_HEADLINES = [
  "Local salmon seen wearing tiny top hats, witnesses confused.",
  "Salmon population reaches record highs as local clicker works tirelessly.",
  "Scientists discover salmon can actually calculate tip, but refuse to do so.",
  "New 'Salmon Premium' subscription service announced: all the water, none of the hooks.",
  "Bear sighting reported near river, says he's 'just here for the vibes'.",
  "Salmon migration delayed due to 'unforeseen underwater construction'.",
  "Ancient Salmon Prophecy fulfilled: 'The Great Clicker' has arrived.",
  "Underwater DJ 'DJ Fin' drops new single: 'Scale of the Century'.",
  "Salmon starts a startup called 'Spawn-ly Fans', stock prices soar.",
  "Intergalactic salmon union demands more oxygen in the vacuum of space.",
];

export const ACHIEVEMENTS = [
  {
    id: 'first_click',
    name: 'First Click',
    description: 'You took your first step into the river.',
    icon: '☝️',
  },
  {
    id: 'century_caught',
    name: '100 Salmon Caught',
    description: 'A hundred fish in the bucket. Not bad.',
    icon: '💯',
  },
  {
    id: 'bear_friend',
    name: 'First Bear Purchased',
    description: 'Nature and industry working hand-in-paw.',
    icon: '🐻',
  },
  {
    id: 'sps_10',
    name: '10 Fish Per Second',
    description: 'The river is starting to flow your way.',
    icon: '⚡',
  },
  {
    id: 'hatchery_tycoon',
    name: 'Hatchery Tycoon',
    description: 'You own a piece of the industrial salmon future.',
    icon: '👑',
  },
  {
    id: 'millionaire',
    name: 'Millionaire',
    description: 'One million salmon in the records.',
    icon: '💎',
  },
  {
    id: 'billionaire',
    name: 'Billionaire',
    description: 'A billion salmon. You are the river king.',
    icon: '🔱',
  },
  {
    id: 'rebirth_1',
    name: 'New Life',
    description: 'Experienced your first rebirth.',
    icon: '🥚',
  },
  {
    id: 'rebirth_5',
    name: 'Evolutionary Cycle',
    description: 'Reborn five times over.',
    icon: '♾️',
  },
];
